--- #YAML:1.0
name:               DBIx-Class-ResultSet-RecursiveUpdate
version:            v0.002
abstract:           like update_or_create - but recursive 
author:
    - Zbigniew Lukasiak <zby@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    DateTime:             0
    DBIx::Class:          0.08011
    DBIx::Class::IntrospectableM2M:  0
    SQL::Translator:      0.08
    Test::More:           0
    version:              0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
